FROM alpine

ARG KG_PERSONAL_PIP_PACKAGES

RUN apk --no-cache --update add python3 py3-pip build-base python3-dev \
libstdc++ && \
pip3 install --upgrade pip && \
pip3 install --upgrade jupyter jupyter_kernel_gateway $KG_PERSONAL_PIP_PACKAGES && \

apk del python3-dev build-base && \

adduser -u 1000 -D jupyter

USER jupyter

ADD jupyter_kernel_gateway_config.py /home/jupyter/.jupyter/jupyter_kernel_gateway_config.py

CMD ["jupyter", "kernelgateway"]
